name: Generate Snake
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *" # Exécution toutes les 12 heures

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/snake.svg

      - name: Publish Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
